lib/OpenSSL.pm6
Manual:ERR_get_error(3): The error code, or 0 if there is no error in the queue.
repeat {} executes the block once regardless of the conditional, so non-errors will get output
Heres two examples of the same test being run twice in a row that this pr appears to have fixed:
localhost:~/perl6/zef$ perl6 -Ilib  t/zef-getter.t
1..3
ok 1 - Created getter
ok 2 - no plugins loaded
err code: 0
Segmentation fault
localhost:~/perl6/zef$ perl6 -Ilib  t/zef-getter.t
1..3
ok 1 - Created getter
ok 2 - no plugins loaded
err code: 0
error:00000000:lib(0):func(0):reason(0)
ok 3 - Used default .get method
ok 4 - Modules were fetched
ok 5 - deleted test modules
1..5
=> Skip error handling: my $e = ERR_get_error() = 0

lib/OpenSSL.pm6, lib/OpenSSL/Bio.pm6, lib/OpenSSL/SSL.pm6
Can now do `$ssl.set-socket(IO::Socket::INET.new(...))` instead of set-fd.
This removes the need to do a C-level connect, and also allows plain-text communication before negotiating a secure connection.
=> Implement wrapping of Perl 6 sockets using BIO functions

lib/OpenSSL.pm6, lib/OpenSSL/Bio.pm6, lib/OpenSSL/SSL.pm6, src/Makefile.in, src/libbuf.c
Enabled by recent NativeCall changes, should have a noticeable performance
improvement.
Also adds write() method for binary data.
=> Switch from CArray to Buf for bulk data

lib/OpenSSL.pm6
`.decode` defaults to utf-8, and I started getting a malformed utf-8 error during 02-socket.t
.unpack('A*')
.decode('latin-1') 
$buf[^$buf.elems]>>.chr.join
seem to all be ok solutions for now. 
Malformed UTF-8 at line 1 col 210
in method decode at src/gen/m-CORE.setting:6314
in method read at /home/nickl/perl6/openssl/lib/OpenSSL.pm6:178
in block <unit> at t/02-socket.t:15
It is strange though, because that test was passing for me yesterday.
=> work around malformed utf-8 in test; s/decode/unpack/

lib/OpenSSL/Err.pm6
It seems that ERR_error_string will randomly segfault when it is called:
nickl@localhost:~/perl6/io-socket-ssl$ perl6 -Ilib -e 'use IO::Socket::SSL; my $ssl = IO::Socket::SSL.new(:host<github.com>, :port(443));'
nickl@localhost:~/perl6/io-socket-ssl$ perl6 -Ilib -e 'use IO::Socket::SSL; my $ssl = IO::Socket::SSL.new(:host<github.com>, :port(80));'
err code: 336130315
error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
nickl@localhost:~/perl6/io-socket-ssl$ perl6 -Ilib -e 'use IO::Socket::SSL; my $ssl = IO::Socket::SSL.new(:host<google.com>, :port(80));'
err code: 336130315
Segmentation fault
This behavior can be averted by putting some statements (like `say 1; say 1; say 1;`) between:
my $e = OpenSSL::ERR::ERR_get_error();
loop {
say OpenSSL::ERR::ERR_error_string($e);
}
The …
=> Explicitly pass a buffer to ERR_error_string [fix segfault]

lib/OpenSSL/Err.pm6
Resolves segfaults on arm7 system when using
ERR_error_string
=> Pass int32 into nativecall function instead of Int

lib/OpenSSL.pm6
Seems like it may be the cause of https://github.com/sergot/http-useragent/issues/105 where a call to `recv($chunked-size)` might return less than `$chunked-size` bytes. This looks like it should be handled in `IO::Socket::SSL` already so it might not be a valid PR; Input is needed
=> Buffer $n bytes before returning

lib/OpenSSL.pm6, t/01-basic.t
OS X ships with OpenSSL 0.9.8 which doesn't support TLSv1.2 and this module fails to  install as a result.
Fix is testing for TLSv1.2 support before using it for the "default"
case and falling back to TLSv1.0 if it's not supported.
=> Fix on OS X

META.info, README.md, lib/OpenSSL/CryptTools.pm6, lib/OpenSSL/EVP.pm6, t/04-crypt.t
- encrypt and decrypt methods are now multisubs with :aes128 and :aes192 candidates
- these now call :cipher candidates for more generalized encryptioon/decryption
- I've defined a CStruct for evp_cipher_st from openssl/evp.h to get key and iv lengths
- tests added to t/07-crypt.h. Existing tests refactored to avoid experimental Buf.unpack
This being use in https://github.com/p6-pdf/perl6-PDF-Tools/blob/openssl-crypt/lib/PDF/Storage/Crypt.pm for AES128 encrypted PDF's.
=> proposed support for aes128 and aes192 encryption

META.info, README.md, lib/OpenSSL/Digest.pm6, lib/OpenSSL/RSATools.pm6, t/05-digest.t
Use the sha1 and sha256 functions in RSATools and drop the dependency
on the Digest module.
I'm planning to use the md5 function in [PDF::Tools](https://github.com/p6-pdf/perl6-PDF-Tools/tree/openssl-md5). Much faster than the pure perl implementation.
=> Provide sha1, sha256 and md5 digest functions.

lib/OpenSSL.pm6
buf8.new has a multi that takes a native array which is much faster.
Passes all the tests.
A profile of `use HTTP::UserAgent; my $ua = HTTP::UserAgent.new; my $response = $ua.get("https://perl6.org"); say $response.content.chars` used to show 1 million+ calls each to `IterationBuffer`'s `push` and `Int`'s `prefix:<-->` and take an average of 2s. After this change it doesn't have either of those 1 million+ calls and takes an average of 1s.
=> Use faster buf8.new multi in read()

t/10-client-ca-file.t
'abspath' method has been removed. Just changed to 'absolute' method
which has been around for some time and should be backward compatible.
=> fix test for Rakudo blead IO::Path

lib/OpenSSL.pm6, lib/OpenSSL/Digest.pm6
buf8.allocate is even faster than creating the buf with a native int
array, plus the code is a little cleaner/simpler. However, it was
introduced in February 2016, so requires a Rakudo built after then.
Passes all the tests.
=> Use buf8.allocate instead of buf8.new

META6.json, README.md, lib/OpenSSL/Digest/MD5.pm6, t/06-digest-md5.t
Added a OO-interface, OpenSSL::Digest::MD5 interface to openssl MD5_Init(), MD5_Update() and MD5_Final() library calls.
=> Add OpenSSL::Digest::MD5

lib/OpenSSL/Ctx.pm6
Needed to allow certificate chains containing intermediate certificates to be imported. Tested locally with corresponding changes made to IO::Socket::Async::SSL, works as expected.
=> Added SSL_CTX_use_certificate_chain_file import

lib/OpenSSL/Ctx.pm6, lib/OpenSSL/NativeLib.pm6, lib/OpenSSL/Stack.pm6, lib/OpenSSL/X509.pm6
More imports related to handling certificates and keys in ssl context.
Also imported low level stack handling functions, although more perlish wrapping is still needed.
Added `sub crypto-lib` to import functions residing in `libcrypto.so`
=> Stack handling functions; Imports from libcrypto.so; More certificate handling functions

lib/OpenSSL.pm6
`infix:<~>` creates new Bufs, so reallocate+slice is less memory hungry.
=> Use reallocate+slice instead of infix:<~> in read

lib/OpenSSL.pm6
According to my interpretation of https://wiki.openssl.org/index.php/Manual:SSL_read(3), if `num` (`$n` here) is larger than the max size of an SSL/TLS record (16k according to https://tools.ietf.org/html/rfc5246#section-6.2.1) it will just return up to a single record.
=> Only allocate buffer to max size of an SSL record

lib/OpenSSL.pm6, lib/OpenSSL/Method.pm6, t/01-basic.t
If no $version was given to OpenSSL.new, it would use the highest
TLS version implemented in the OpenSSL library. This is a problem
when you access, via e.g. the WWW module which gives you no access
to the OpenSSL instance, a server which only implements older TLS.
Now, a version negotiating TLS method is used instead if no
explicit $version is requested. Prior to OpenSSL 1.1.0, this
was SSLv23_method() and was then renamed to TLS_method().
See https://wiki.openssl.org/index.php/SSL/TLS_Client#Context_Setup
The OpenSSL documentation SSL_CTX_new(3) recommends to use the
version-flexible methods in applications, so this module should
at least make it available in some form. The manpage even says that
the version-specific methods are deprecated with OpenSSL 1.1.0,
so I guess it isn't too …
=> OpenSSL: Negotiate TLS version by default

META6.json, lib/OpenSSL/Stack.pm6, lib/OpenSSL/Version.pm6, t/07-version.t, t/10-client-ca-file.t
This pull request fixes issue #62. The patch adds the module OpenSSL::Version and the functions version_num and version. OpenSSL::Stack uses version_num to define sk_num, sk_value and sk_free, which have been renamed in OpenSSL 1.1.
As mentioned in #64 Rakudo HEAD currently seems to be broken on Windows. See https://ci.appveyor.com/project/voegelas/openssl/build/1.0.17 for a successful build with Rakudo 2018.06. See https://travis-ci.org/voegelas/openssl for a successful Travis build.
=> Add OpenSSL::Version

lib/OpenSSL/SSL.pm6
OpenSSL.set-server-name() and the test "15-issue-36.t" fail on Windows as the type "long" is 32-bit on that platform. This fix replaces "int64" by "long" in the signature of SSL_ctrl().
Note: I had to change "appveyor.yml" as follows in my repository in order to get a stable Rakudo release that is able to run the tests.
```
- appveyor-retry git clone https://github.com/rakudo/rakudo.git %APPVEYOR_BUILD_FOLDER%\..\rakudo
- cd %APPVEYOR_BUILD_FOLDER%\..\rakudo
+    - git checkout 2018.06
```
=> Fix SSL_ctrl on Windows

lib/OpenSSL/Stack.pm6
This patch adds a check for LibreSSL to OpenSSL::Stack. LibreSSL is based on OpenSSL 1.0.2 but returns the version number 2.0.0.
This change fixes the failure in t/10-client-ca-file.t, which is reported in issue #66. The failures in t/01-basic.t are not fixed by this patch.
```
> $*DISTRO
openbsd (6.3)
> use OpenSSL::Version
Nil
> OpenSSL::Version::version()
LibreSSL 2.7.2
> sprintf "%x", OpenSSL::Version::version_num()
20000000
```
See also https://github.com/libressl-portable/openbsd/blob/master/src/lib/libcrypto/opensslv.h
=> Check for LibreSSL

META6.json, lib/OpenSSL/Method.pm6, t/01-basic.t
Do not check OpenSSL specific attribute and properly document it, which allows testing on platform where LibreSSL is used pass.
Fixes https://github.com/sergot/openssl/issues/63
Fixes https://github.com/sergot/openssl/issues/53
=> Unbreak LibreSSL implementation testing

.gitignore, .travis.yml, Build.pm6, META6.json, appveyor.yml, lib/OpenSSL/NativeLib.pm6
Currently we cannot install OpenSSL module properly by `zef install OpenSSL` in macOS.
This is because OpenSSL module tries to load libssl/libcrypto from /usr/lib, but they are *incompatible*.
This PR adds Build.pm6, where we probe openssl libraries by `brew --prefix openssl`.
I think it is reasonable to prefer homebrew's openssl;
[Net::SSLeay](https://github.com/radiator-software/p5-net-ssleay/blob/f9ed3412d670edb08d7c9e01e7f92f99602ac728/Makefile.PL#L309), [ruby-build](https://github.com/rbenv/ruby-build/blob/0bd64d37990908876e895aa471685d937f01a034/bin/ruby-build#L1074), [python-build](https://github.com/pyenv/pyenv/blob/6656066d4fefba64ae247956bb35399f98a399c4/plugins/python-build/bin/python-build#L1392) also prefer homebrew's openssl.
This PR will fix #80, #81.
=> Fix macOS build; probe openssl libraries in Build.pm6

Build.pm6
I created PR #83 (and it was merged, thanks!), where we used `brew --prefix openssl` to probe openssl libraries.
But it turns out that `brew --prefix openssl` prints a directory even if openssl formula is not installed. I'm sorry.
```
❯ brew --prefix --help
Usage: brew --prefix [--unbrewed] [--installed] [formula ...]
...
If formula is provided, display the location where formula is or would be
installed.
...
--installed                  Outputs nothing and returns a failing
status code if formula is not installed.
```
This PR adds `--installed` option  to `brew --prefix` command so that `brew --prefix` prints a directory only if openssl formula is actually installed.
=> use --installed option while executing brew

Build.pm6, META6.json, appveyor.yml
When updating a native library that an existing precompiled raku module uses there will still be references to the old (now non-existing) native library. This change works around the issue by deleting the precomp files as part of its build step. This helps work around #82
=> Delete precomp files when rebuilding 

Build.pm6, META6.json
This reverts commit dcf88a825c65b2727b385452abec5af79811c162.
As described in https://github.com/sergot/openssl/issues/87 that commit
(which is totally fine in principle) unveiled some weird underlying
issue with the precompilation of dependencies for the OpenSSL module.
So, this revert is only a bandaid to unbreak installation of the latest
version (at least on Debian 10)."
=> Revert "Use JSON::Fast to handle json"

lib/OpenSSL/NativeLib.pm6
Without this testing against OpenSSL installed to a CUR::Staging repo fails to find a module in the 'site' repo (despite only having a dependency on NativeCall which is in the 'core' repo).
=> Only deserialize at compile time

Build.pm6, META6.json
This reverts commit 20e89d2e55e4023e0a31dafd7d4bbf2cbfb36a95.
I believe that @patrickbkr and @niner found the real fix for the
spurious failures in OpenSSL::RSAKey with b37d5a0c8b. So the revert,
which only served as a bandaid, is no longer needed.
=> Revert "Revert "Use JSON::Fast to handle json" (#88)"

.github/workflows/test.yml, lib/OpenSSL/NativeLib.rakumod
Rakudo recently started emitting deprecation messages when `%?RESOURCES` was treated like a path string (see https://github.com/rakudo/rakudo/pull/5507). That affects these openssl bindings because a windows-specific hack was using the base file name of a `%?RESOURCE` entry, which would cause the aforementioned deprecation messages to be emitted. This PR reworks the hack to not depend on any part of the path name.
=> Rework Windows resources hack to not depend on resource path strings

lib/OpenSSL.rakumod
Do so by adding simple (non concurrency safe) guards.
=> Fix segfaults when double closing
